### ISSUE TITLE
panic - get_argument_big_uint not yet implemented when making contract call using elrond-wasm-debug

### ISSUE THREAD

**Issue by willemolding** [ElrondNetwork/elrond-wasm-rs#1]
Using version 0.5.2

This issue can be replicated by running the debug tests in the [sc-examples](https://github.com/ElrondNetwork/sc-examples-rs) simple-coin contract.

Making a call to a contract function that does not use a BigUint seems to work fine (I have only tested calling contracts that take Address in their parameters) 

Calling a function with a param that is a BigUint causes the following panic:"

```shell
thread 'main' panicked at 'get_argument_big_uint not yet implemented', /home/$USER/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13:23
```

**Comment by andrei-marinica** [comment]
This should be fixed as of version 0.7.1. If you have trouble upgrading to the latest version, please let me know and I will help.
