### ISSUE TITLE
Naming a parameter `amount` in a proxy remote call definition results in no data being passed

### ISSUE THREAD

**Issue by willemolding** [ElrondNetwork/elrond-wasm-rs#2]
I came across this strange bug. If I define a proxy trait to make a cross contract call as follows
```rust
#[elrond_wasm_derive::callable(TestProxyImpl)]
pub trait TestProxy {
    #[callback(remote_call_callback)]
    fn remote_call(&self,
        amount: BigUint
    );
}
```
The call appears to work but **no data is passed to the remote function.**

Changing the parameter name to anything else e.g.
```rust
#[elrond_wasm_derive::callable(TestProxyImpl)]
pub trait TestProxy {
    #[callback(remote_call_callback)]
    fn remote_call(&self,
        token_amount: BigUint
    );
}
```
allows the calls to work correctly. 

An minimal example to replicate the issue can be found here https://github.com/willemolding/elrond-callback-example/tree/amount-param-error

**Comment by andrei-marinica** [comment]
Hi!
Thank you for the detailed report.
The problem is caused by a variable name clash with a variable generated inside the elrond_wasm_derive::callable macro. We are fixing it in the next release.
