### ISSUE TITLE
SC send() is not reflected on wallet transactions feed

### ISSUE THREAD

**Issue by ViictorD** [ElrondNetwork/elrond-wasm-rs#418]
Hi devs,

I was supprised when i was testing the `direct_egld()` function on devnet, that it is not shown on the transactions feed on the devnet-wallet.

So currently if someone receive funds from a SC, the wallet owner have to way to know that he received it. Excepte the balance increase. I'm guessing there is no notification on the maiar app either.

And for example if i just want to send a message from a SC to an address to say "You can withdraw your fund now", it just doesn't show up, and doesn't notify on the app.

Can you implement that ?
Thank you

**Comment by dorin-iancu** [comment]
You don't see it as a transaction, because it isn't. It's part of the original transaction. You might be able to see it in the SCResults tab.
