### ISSUE TITLE
Exception while checking contract balance : fatal error: exitsyscall: syscall frame is no longer valid

### ISSUE THREAD

**Issue by ysfkel** [ElrondNetwork/elrond-wasm-rs#518]
In mandos test , 
when contract calls blockchain api to get esdt balance of the contract , the following exception happens, even though in the test, I  updated token balance of the contract using setState

ERROR 
Scenario: withdraw.scen.json ... fatal error: exitsyscall: syscall frame is no longer valid

Mandos setstate updates contract esdt balance

          "sc:test_contract”: {
                …
                "esdt":{
                    "str:TICKER-0a1b2c":"400,000,000,000"
                }
           }

The line that causes the error is this 

   self.blockchain().get_sc_balance(&token, 0)

FULL EXCEPTION 

Scenario: withdraw.scen.json ... fatal error: exitsyscall: syscall frame is no longer valid
 
goroutine 1 [running, locked to thread]:
runtime.throw(0x45fc36b, 0x2d)
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/runtime/panic.go:1116 +0x72 fp=0xc00051afc8 sp=0xc00051af98 pc=0x4037112
runtime.exitsyscall()
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/runtime/proc.go:3225 +0x22c fp=0xc00051aff8 sp=0xc00051afc8 pc=0x406536c
runtime.cgocall(0x4460ca0, 0xc00051b060, 0x1)
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/runtime/cgocall.go:152 +0x9e fp=0xc00051b030 sp=0xc00051aff8 pc=0x4005fbe
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/wasmer._Cfunc_wasmer_instance_call(0x600000c0e6d0, 0x600000008dc0, 0xc0002e8ae0, 0x0, 0xc0002e8b00, 0xc000000000, 0xc000000002)
        _cgo_gotypes.go:449 +0x4d fp=0xc00051b060 sp=0xc00051b030 pc=0x4304ced
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/wasmer.cWasmerInstanceCall(...)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/wasmer/bridge.go:241
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/wasmer.callWasmFunction(0x600000c0e6d0, 0xc0005fcd78, 0x8, 0x0, 0x4a96fa8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/wasmer/function_wrapper_helpers.go:82 +0x1bf fp=0xc00051b0d8 sp=0xc00051b060 pc=0x4300f9f
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/wasmer.createExportedFunctionWrapper.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/wasmer/instance_helpers.go:144 +0x190 fp=0xc00051b190 sp=0xc00051b0d8 pc=0x4307370
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/host.(*vmHost).callSCMethod(0xc0003500f0, 0xc00006b000, 0x4c75)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwen/host/execution.go:874 +0x494 fp=0xc00051b268 sp=0xc00051b190 pc=0x43f3f34
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/host.(*vmHost).doRunSmartContractCall(0xc0003500f0, 0xc0000a81e0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwen/host/execution.go:186 +0x6d7 fp=0xc00051b3a0 sp=0xc00051b268 pc=0x43edff7
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/host.(*vmHost).RunSmartContractCall.func2()
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwen/host/arwen.go:353 +0x3c fp=0xc00051b3d0 sp=0xc00051b3a0 pc=0x43f4e3c
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/host.TryCatch(0xc00051b480, 0xc00051b470, 0x45f1b50, 0x1a)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwen/host/arwen.go:384 +0x6c fp=0xc00051b420 sp=0xc00051b3d0 pc=0x43e466c
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwen/host.(*vmHost).RunSmartContractCall(0xc0003500f0, 0xc0000a81e0, 0x0, 0x0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwen/host/arwen.go:365 +0x24b fp=0xc00051b4e0 sp=0xc00051b420 pc=0x43e452b
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwenmandos.(*ArwenTestExecutor).scCall(0xc000130240, 0xc0004527a1, 0xd, 0xc00013e120, 0x5f5e100, 0x0, 0x0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwenmandos/stepRunTx.go:240 +0x342 fp=0xc00051b668 sp=0xc00051b4e0 pc=0x445d222
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwenmandos.(*ArwenTestExecutor).executeTx(0xc000130240, 0xc0004527a1, 0xd, 0xc00013e120, 0x0, 0x0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwenmandos/stepRunTx.go:81 +0x1d2 fp=0xc00051b7f8 sp=0xc00051b668 pc=0x445b112
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwenmandos.(*ArwenTestExecutor).ExecuteTxStep(0xc000130240, 0xc0002eaac0, 0xc00051b8a0, 0x445f982, 0xc00014e930)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwenmandos/execScenario.go:138 +0x125 fp=0xc00051b868 sp=0xc00051b7f8 pc=0x4451265
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwenmandos.(*ArwenTestExecutor).ExecuteStep(0xc000130240, 0x4794760, 0xc0002eaac0, 0x0, 0x0)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwenmandos/execScenario.go:57 +0x111 fp=0xc00051b8b0 sp=0xc00051b868 pc=0x4450351
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/arwenmandos.(*ArwenTestExecutor).ExecuteScenario(0xc000130240, 0xc0001b9f40, 0x479e660, 0xc0001286c0, 0x5d, 0xc0001b9f40)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/arwenmandos/execScenario.go:31 +0x1e5 fp=0xc00051b938 sp=0xc00051b8b0 pc=0x4450165
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/mandos-go/controller.(*ScenarioRunner).RunSingleJSONScenario(0xc00051bf38, 0xc0001aa1e0, 0x5d, 0xc000132301, 0x5d, 0x208f4ae87)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/mandos-go/controller/scenarioOne.go:38 +0xc8 fp=0xc00051b988 sp=0xc00051b938 pc=0x4419f68
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/mandos-go/controller.(*ScenarioRunner).RunAllJSONScenariosInDirectory.func1(0xc0001aa1e0, 0x5d, 0x47a0a60, 0xc00011d860, 0x0, 0x0, 0x12, 0xc00051bb10)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/mandos-go/controller/scenarioDir.go:33 +0x334 fp=0xc00051ba88 sp=0xc00051b988 pc=0x441ab54
path/filepath.walk(0xc0001aa1e0, 0x5d, 0x47a0a60, 0xc00011d860, 0xc00051bd60, 0x0, 0x0)
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/path/filepath/path.go:360 +0x423 fp=0xc00051bb60 sp=0xc00051ba88 pc=0x40ead63
path/filepath.walk(0xc00012c140, 0x4a, 0x47a0a60, 0xc00011d6c0, 0xc00051bd60, 0x0, 0x4a)
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/path/filepath/path.go:384 +0x2fe fp=0xc00051bc38 sp=0xc00051bb60 pc=0x40eac3e
path/filepath.Walk(0xc00012c140, 0x4a, 0xc000159d60, 0xc00012c140, 0x4a)
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/path/filepath/path.go:406 +0x105 fp=0xc00051bc98 sp=0xc00051bc38 pc=0x40eaea5
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/mandos-go/controller.(*ScenarioRunner).RunAllJSONScenariosInDirectory(0xc000159f38, 0x208f4ae87, 0x4a, 0x0, 0x0, 0x45e8b81, 0xa, 0xc000159e40, 0x0, 0x0, ...)
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/mandos-go/controller/scenarioDir.go:24 +0x1d4 fp=0xc00051bdd8 sp=0xc00051bc98 pc=0x4419a54
github.com/ElrondNetwork/arwen-wasm-vm/v1_4/cmd/mandostestcli.MandosTestCLI()
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/cmd/mandostestcli/mandosTestCLI.go:71 +0x894 fp=0xc00051bf78 sp=0xc00051bdd8 pc=0x4460774
main.main()
        /Users/myuser/elrondsdk/vmtools/v1.4.32/wasm-vm-1.4.32/cmd/test/mandosTestLegacy.go:7 +0x25 fp=0xc00051bf88 sp=0xc00051bf78 pc=0x4460905
runtime.main()
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/runtime/proc.go:204 +0x209 fp=0xc00051bfe0 sp=0xc00051bf88 pc=0x40398e9
runtime.goexit()
        /Users/myuser/elrondsdk/golang/go1.15.2/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00051bfe8 sp=0xc00051bfe0 pc=0x4069721

**Comment by dorin-iancu** [comment]
Same as #623
