### ISSUE TITLE
error when compiling `elrond-wasm` v0.26.0

### ISSUE THREAD

**Issue by theadriann** [ElrondNetwork/elrond-wasm-rs#558]
Description:
Bounds of 'a are probably not defined in this scope.

Reference:
https://github.com/ElrondNetwork/elrond-wasm-rs/blob/d39c38ca220bc8ebd4658968bcbf3b3fda38de3f/elrond-wasm/src/types/managed/managed_vec_item.rs#L35

```
error: Missing required bounds on Ref
--> /.../vendor-rust/registry/src/github.com-1ecc6299db9ec823/elrond-wasm-0.26.0/src/types/managed/managed_vec_item.rs:35:5
|
35 |     type Ref<'a>: Borrow<Self>;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^-
|                               |
|                               help: add the required where clauses: `where Self: 'a`
```

**Comment by theadriann** [comment]
I was compiling with Rust `rustc 1.59`, upgrading to `rustc 1.60.0-nightly (9ad5d82f8 2022-01-18)` fixed the issue.

**Comment by mrazvanalex** [comment]
Don't forget to update via erdpy **deps install rust --overwrite, not via rustup**
