### ISSUE TITLE
Enable the transfer of multiple ESDT tokens in a single call to a contract method

### ISSUE THREAD

**Issue by hiddentao** [ElrondNetwork/elrond-wasm-rs#59]
At present you can transfer a single ESDT token when calling a contract method. It would be good if multiple ESDT tokens could be transferred in a call to a contract to makes it easier to e.g. add a token pair to a liquidity pool in future applications.

**Comment by andrei-marinica** [comment]
The current Elrond architecture does not support this. A single payment is accepted at one time: either EGLD, or a single ESDT token. This is among other things for security reasons.
DEX-es will accept payment in one coin and send another. To make liquidity pairs, it can be performed with 2 transactions, one for one coin and one for the other.

**Comment by hiddentao** [comment]
Can I send eGLD as well as a token in a single transaction?


--
Ramesh Nair


Director
HiddenTao Ltd (UK company no. 6807289)


http://hiddentao.com
https://github.com/hiddentao
https://www.linkedin.com/in/hiddentao
