### ISSUE TITLE
egld-esdt-swap - global mint is no more enabled, use local mint

### ISSUE THREAD

**Issue by Dev4Elrond** [ElrondNetwork/elrond-wasm-rs#598]
After successful deploy and issue the mint transaction has the following error: 
global mint is no more enabled, use local mint

Both in play.elrond.com and when using this example.

**Comment by Dev4Elrond** [comment]
@andrei-marinica and @dorin-iancu you seem to be the experts here. :-)

**Comment by dorin-iancu** [comment]
You were probably using a very old version. The latest version (for quite some time) uses local mint/local burn.
