### ISSUE TITLE
[MultisigContract] A board member can block the actions of all the other board members

### ISSUE THREAD

**Issue by cleanunicorn** [ElrondNetwork/elrond-wasm-rs#67]
**Description**

An action has to go through a number of steps in order to be executed.

The first step is proposing an action. A board member or a proposer can propose an action.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L99-L106

The second step is signing that action. Any board members can sign that action.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L212-L217

The third step is executing the action, once the quorum was reached.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L305-L306

Before the action is executed, any board member can withdraw their signature by calling `unsign`.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L228-L233

The `unsign` method, to remove blockchain state bloat, removes the action once all of the board members withdrew all of their signatures.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L245-L248

This creates a race condition issue where one of the board members, if they don't agree with an action, watch the blockchain for that action to be proposed, are the first ones to sign the action, and immediately unsign the action, removing the possibility for any other board member to sign and execute that action.

Even if the other board members want to remove the misbehaving board member from the quorum, they need to go through the same process of proposing, signing and executing the action. If the misbehaving board member watches the contract for that proposal can race against all the other board members sign and unsign the action, removing it from the proposed actions. This way the board members, if they are successfully fronrun, they can't perform any actions in the MultisigContract they should have control over.

**Recommendation**

Do not empty the state if there are no signers left.

**Referrences**

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/87e769e6107278b23fbd4887e3e7c3c7cd0aa154/contracts/examples/multisig/src/lib.rs#L245-L248

**Comment by andrei-marinica** [comment]
This is actually not so bad, actually.
The scenario described by you can happen if an action proposer is not a board member. An action proposed by a board member gets 1 signature from it proposer from the beginning, so it cannot be cleaned up by someone else against the proposer's will.
If a board member goes rogue and needs to be removed, the removal action can be proposed by another board member. The rogue member can do nothing about it.
