### ISSUE TITLE
Reimplement execute_on_dest_context_custom_range

### ISSUE THREAD

**Issue by gfusee** [ElrondNetwork/elrond-wasm-rs#703]
Hi,

elrond-wasm-rs 0.31.0 removed execute_on_dest_context_custom_range. This function was the only way to get nested contracts calls results. This feature was very useful to interact with some complex contracts (like maiar dex). Is it possible to reimplement this function?

Thank you

**Comment by dorin-iancu** [comment]
It's not needed anymore, as now execute_on_dest_context filters nested results automatically.
