### ISSUE TITLE
Airdrop smart contract issue while sending tokens

### ISSUE THREAD

**Issue by buff3r0verfl0w** [ElrondNetwork/elrond-wasm-rs#732]
I'm doing airdrop sc in rust but elrond network fails tx
![image1](https://user-images.githubusercontent.com/98341994/170474328-27d4afde-2b75-45b9-947f-82b5b683a331.png)
![image2](https://user-images.githubusercontent.com/98341994/170474406-6fe26c88-0c15-4e0b-9a8d-1ff331011f15.png)
```rust
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, TypeAbi)]
pub struct Row<M: ManagedTypeApi> {
    pub address: ManagedAddress<M>,
    pub amount: BigUint<M>,
}

#[elrond_wasm::contract]
pub trait Airdrop {
    #[only_owner]
    #[endpoint]
    fn distribution(&self, table: Vec<Row<Self::Api>>) {
        let (output_token, _) = self.output_token().get();
        for row in &table {
            self.send().direct(&row.address, &output_token, 0, &row.amount, &[]);
        }
    }
}
```

**Comment by dorin-iancu** [comment]
You're likely trying to send tokens to a smart contract. Even if your SC is payable, others may not be.
