### ISSUE TITLE
EgldOrEsdtTokenPayment doesn't implement ManagedVecItem

### ISSUE THREAD

**Issue by gfusee** [ElrondNetwork/elrond-wasm-rs#771]
Hi! It is impossible to create a ManagedVec of EgldEsdtTokenPayment elements because it doesn't implement the trait ManagedVecItem.

**Comment by dorin-iancu** [comment]
There is no reason to have such a vec. There is also no API that will let you use it. Keep EGLD amount separate, and a ManagedVec<EsdtTokenPayment> for ESDTs.

If for whatever reason you REALLY need such a vec, you can create a custom struct.
