### ISSUE TITLE
TxResult returned from the  execute_tx method on BlockchainStateWrapper issues on async smart contract to smart contract calls

### ISSUE THREAD

**Issue by newtmex** [ElrondNetwork/elrond-wasm-rs#791]
For context I have these endpoint and callback in my contract code

1. Endpoint
    ```rust
    #[endpoint]
    fn register(&self) {
        let caller: ManagedAddress = self.blockchain().get_caller();
        let delegation_addr = self.delegation_sc_addr().get();

        self.delegation_proxy(delegation_addr)
            .get_user_active_stake(&caller)
            .async_call()
            .with_callback(self.callbacks().process_registration())
            .call_and_exit();
    }
    ```
1. Callback
   ```rust
     #[callback]
    fn process_registration(&self, #[call_result] result: ManagedAsyncCallResult<BigUint>) {
        // address must have active stake on the delegation contract
        match result {
            ManagedAsyncCallResult::Ok(active_stake) => {
                require!(
                    active_stake != BigUint::from(0usize),
                    "no active stake for user"
                );
            }
            ManagedAsyncCallResult::Err(err) => {
                sc_panic!(&err.err_msg);
            }
        };
    }
   ```

Then, I have this Rust test snippet
```rust
    let not_staked_address = blockchain_wrapper.create_user_account(&rust_zero);
    blockchain_wrapper
        .execute_tx(&not_staked_address, &cg_wrapper, &rust_zero, |sc| {
            sc.register();
        })
        .assert_error(4, "no active stake for user");
```

For this case, the test should pass with the expected error `no active stake for user`, but it fails saying that the transaction was successful.

If I change the call from being asynchronous _(i.e using the `execute_on_dest_context` method)_, then the test passes.

Seems the testing framework is not doing all the necessary checks or am I doing something wrong?

**Comment by newtmex** [comment]
Here's the test result:

```
failures:

---- register_test stdout ----
thread 'register_test' panicked at 'Box<dyn Any>', /folder/.cargo/registry/src/github.com-1ecc6299db9ec823/elrond-wasm-debug-0.34.0/src/api/send_api_mock.rs:161:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
no active stake for user
thread 'register_test' panicked at 'Box<dyn Any>', /folder/.cargo/registry/src/github.com-1ecc6299db9ec823/elrond-wasm-debug-0.34.0/src/api/error_api_mock.rs:18:9
thread 'register_test' panicked at 'Tx error message mismatch. Want status 4, message "no active stake for user". Have status 0, message ""', /folder/.cargo/registry/src/github.com-1ecc6299db9ec823/elrond-wasm-debug-0.34.0/src/tx_mock/tx_result.rs:91:9
```


It seems the after the panic for `no active stake for user` occurred, somehow the debug framework did not catch it.

**Comment by dorin-iancu** [comment]
Hey. This is just how it works on the actual blockchain as well. The initial transaction is successful, even if the callback threw an error. What your `assert_error` checks is for the initial transaction, which completed successfully and launched the async call.

For now, checking errors in callbacks is not something we're willing to invest time on. You'll have to check changes in your state according to your callback's logic.

**Comment by newtmex** [comment]
I also tried to assert on the sate of the contract after code execution, but nothing worked.

It seems the issue is because the `call_and_exit` method that must be invoked after the `async_call` method terminates program execution.

So anything we try to run after invoking a sc-to-sc endpoint on our sc during test will not run within the scope that endpoint invocation is made.
