### ISSUE TITLE
blockchain().get_gas_limit() implementation of BlockchainApi for DebugApi

### ISSUE THREAD

**Issue by newtmex** [ElrondNetwork/elrond-wasm-rs#808]
Is there a reason for this cap on `gas_limit` for `async_callback_tx_input` as seen here?
https://github.com/ElrondNetwork/elrond-wasm-rs/blob/296e34ae4ffd8333c7a2cb39b105dd2d0c5c5db4/elrond-wasm-debug/src/tx_mock/tx_async_call_data.rs#L59 

When `self.blockchain().get_gas_limit()` is called in a smart contract's callback that is called after an async call, this value defaults to 1000 in the Rust Framework test.

Is this hard cap for a reason? Shouldn't it be set by the user?

@andrei-marinica

**Comment by andrei-marinica** [comment]
The is no gas in the Rust tests, because we do not model the WebAssembly instructions. That is why the gas limit could have been any value. Making it 0, though, was causing some out-of-gas issues. The `1000` value is pretty arbitrary, could have been `1`. Will need to revise this code.
