### ISSUE TITLE
`#[only_owner]` attribute by Rust Testing Framework

### ISSUE THREAD

**Issue by newtmex** [ElrondNetwork/elrond-wasm-rs#847]
Seems like a bug; the Rust Testing Framework does not handle endpoints annotated with the `#[only_owner]` as expected.

**Comment by andrei-marinica** [comment]
The Rust Testing Framework, as it is, gives you access directly to the contract methods, so annotations do not come into effect in this case (and cannot for that matter).

There is an alternate way to test contracts in a setting more akin to the real blockchain, check this out: https://github.com/ElrondNetwork/elrond-wasm-rs/blob/master/contracts/examples/multisig/tests/multisig_rust_test_v2.rs
It's closer to mandos, but in a programmatic Rust way.

**Comment by newtmex** [comment]
Thanks @andrei-marinica for the reply.

I will study the file.

(Also thanks for the `elrond-interact-snippets` library, it's a very useful tool.
